# Deploy server and client in different stages because
# Heroku only allows for 1 concurrent build
stages:
  - test
  - migrate_db
  - server_deploy
  - client_deploy

test_server:
  image: python:3.7
  stage: test
  script:
    - cd ./
    # - pip install pipenv
    # - cd ./server
    # - pipenv install
    # - echo "=============================================="
    # - echo "============= RUNNING TESTS NOW =============="
    # - echo "----------------------------------------------"
    # - pipenv run tests
    # - echo "=============================================="
    # - echo "============ TESTING DOCSTYLE NOW ============"
    # - echo "----------------------------------------------"
    # - pipenv run pydocstyle

migrate_db:
  image: python:3.7
  stage: migrate_db
  script:
    - cd ./
    # - pip install pipenv
    # - cd ./server
    # - pipenv install
    # - pipenv run upgrade
  only:
    - master

deploy_server:
  image: ruby:2.2
  stage: server_deploy
  script:
    - cd ./
    # - cd ./server
    # - apt-get update -qy
    # - apt-get install -y ruby-dev python-dev python-pip
    # - gem install dpl -v 1.10.14
    # - gem install multipart-post -v 2.1.1
    # - gem install faraday -v 0.17.1
    # - gem install rendezvous -v 0.1.3
    # - gem install netrc -v 0.11.0
    # - gem install dpl-heroku -v 1.10.14
    # - dpl --provider=heroku --app=$HEROKU_SERVER_APP --api-key=$HEROKU_API_KEY
  only:
    - master
    - dev

deploy_client:
  image: ruby:2.2
  stage: client_deploy
  script:
    - cd ./
    # - cd ./client
    # - apt-get update -qy
    # - apt-get install -y ruby-dev
    # - gem install dpl -v 1.10.14
    # - gem install multipart-post -v 2.1.1
    # - gem install faraday -v 0.17.1
    # - gem install rendezvous -v 0.1.3
    # - gem install netrc -v 0.11.0
    # - gem install dpl-heroku -v 1.10.14
    # - dpl --provider=heroku --app=$HEROKU_CLIENT_APP --api-key=$HEROKU_API_KEY
  only:
    - master
    - dev
