# Deploy server and client in different stages because
# Heroku only allows for 1 concurrent build
stages:
  - test
  - server_deploy
  - client_deploy

test_server:
  image: python:3.7
  stage: test
  script:
    - pip install pipenv
    - cd ./server
    - pipenv install
    - echo "=============================================="
    - echo "============= RUNNING TESTS NOW =============="
    - echo "----------------------------------------------"
    - pipenv run pytest
    - echo "=============================================="
    - echo "============ TESTING DOCSTYLE NOW ============"
    - echo "----------------------------------------------"
    - pipenv run pydocstyle

deploy_server:
  image: ruby:2.2
  stage: server_deploy
  script:
    - cd ./server
    - apt-get update -qy
    - apt-get install -y ruby-dev python-dev python-pip
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_SERVER_APP --api-key=$HEROKU_API_KEY
  only:
    - master
    - dev

deploy_client:
  image: ruby:2.2
  stage: client_deploy
  script:
    - cd ./client
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_CLIENT_APP --api-key=$HEROKU_API_KEY
  only:
    - master
    - dev
