version: "3.3"

services:
  db:
    restart: always
    image: sameersbn/postgresql:10-2
    ports:
      - "5432:5432"
    environment:
      - DB_USER=admin
      - DB_PASS=password
      - DB_NAME=gojap
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
