"""empty message

Revision ID: 23d4d4189022
Revises: 7d34a32c8246
Create Date: 2020-01-28 00:40:22.801996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d4d4189022'
down_revision = '7d34a32c8246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'status')
    # ### end Alembic commands ###
