"""empty message.

Revision ID: 3d367097fb84
Revises: 894b6b9d2427
Create Date: 2020-01-29 22:01:04.229305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d367097fb84'
down_revision = '894b6b9d2427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_user_command', 'user_command', [
                                'command_id', 'user_id'])
    op.add_column('jap_event', sa.Column(
        'status', sa.Integer(), nullable=False))
    op.create_unique_constraint('uc_table_item', 'command_item', [
                                'table_id', 'item_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jap_event', 'status')
    # ### end Alembic commands ###
