"""empty message

Revision ID: 3df92cdd2df0
Revises: 
Create Date: 2020-02-01 17:50:45.325991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df92cdd2df0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_user_command', 'user_command', [
                                'command_id', 'user_id'])
    op.create_unique_constraint('uc_table_item', 'command_item', [
                                'table_id', 'item_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_table_item', 'command_item', type_='unique')
    op.drop_constraint('uc_user_command', 'user_command', type_='unique')
    # ### end Alembic commands ###
