"""empty message

Revision ID: 58777c573782
Revises: f363980b4f4c
Create Date: 2020-01-28 00:43:16.028659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58777c573782'
down_revision = 'f363980b4f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'status')
    # ### end Alembic commands ###
