"""empty message

Revision ID: 605fe448caf3
Revises: 9da78184af12
Create Date: 2020-02-04 14:44:05.200110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605fe448caf3'
down_revision = '9da78184af12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jap_event', sa.Column(
        'creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('jap_event_created_by_fkey',
                       'jap_event', type_='foreignkey')
    op.create_foreign_key(None, 'jap_event', 'user', ['creator_id'], ['id'])
    op.drop_column('jap_event', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jap_event', sa.Column(
        'created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jap_event', type_='foreignkey')
    op.create_foreign_key('jap_event_created_by_fkey',
                          'jap_event', 'user', ['created_by'], ['id'])
    op.drop_column('jap_event', 'creator_id')
    # ### end Alembic commands ###
