"""empty message

Revision ID: 61882b054a0e
Revises: 3d367097fb84
Create Date: 2020-01-29 22:14:55.296138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61882b054a0e'
down_revision = '3d367097fb84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jap_event', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###
    op.create_unique_constraint('uc_user_command', 'user_command', [
                                'command_id', 'user_id'])
    op.create_unique_constraint('uc_table_item', 'command_item', [
                                'table_id', 'item_id'])
                                
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jap_event', 'status')
    # ### end Alembic commands ###
