"""empty message

Revision ID: 6756c255f8b1
Revises: d56d52e4495f
Create Date: 2020-01-27 23:24:32.413348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6756c255f8b1'
down_revision = 'd56d52e4495f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_commands', sa.Column('order_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_commands', 'order_amount')
    # ### end Alembic commands ###
