"""empty message

Revision ID: a12fb2b6d441
Revises: 9da78184af12
Create Date: 2020-02-04 16:07:59.205145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12fb2b6d441'
down_revision = '9da78184af12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_menus', sa.Column(
        'index_in_menu', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_menus', 'index_in_menu')
    # ### end Alembic commands ###
