"""empty message

Revision ID: f4cc719ac709
Revises: 6756c255f8b1
Create Date: 2020-01-27 23:49:59.573223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cc719ac709'
down_revision = '6756c255f8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('command_id', sa.Integer(), nullable=True),
    sa.Column('order_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['command_user.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item_commands')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_commands',
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('command_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['command_user.id'], name='item_commands_command_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='item_commands_item_id_fkey'),
    sa.PrimaryKeyConstraint('item_id', 'command_id', name='item_commands_pkey')
    )
    op.drop_table('item_command')
    # ### end Alembic commands ###
