"""empty message

Revision ID: fe7e5a665853
Revises: 58777c573782
Create Date: 2020-01-28 01:26:31.904249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe7e5a665853'
down_revision = '58777c573782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('command_id', sa.Integer(), nullable=True),
    sa.Column('order_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['command_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item_command')
    op.drop_table('command_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('command_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], name='command_user_table_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='command_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='command_user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('item_command',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('command_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['command_user.id'], name='item_command_command_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='item_command_item_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='item_command_pkey')
    )
    op.drop_table('user_command')
    op.drop_table('command_item')
    # ### end Alembic commands ###
